name: Keep Apps Awake

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit apps
        run: |
          curl -I -L --max-time 60 "https://coupled-coreshell-nanostructures-library-materials-sij.streamlit.app" || true
          curl -I -L --max-time 60 "https://multilayer-sphere-app-jgss9lz64q8rqefm8xecfq.streamlit.app" || true
          curl -I -L --max-time 60 "https://gold-disk-spectrum-app-sij-umk.streamlit.app" || true
